# Generated by Django 5.1.4 on 2025-04-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_first_name_student'),
        ('app', '0003_student'),
    ]

    operations = [
    ]
