# Generated by Django 5.1.4 on 2025-04-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customuser_first_name'),
        ('app', '0004_merge_20250426_1146'),
    ]

    operations = [
    ]
