# Generated by Django 3.0.5 on 2025-04-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customuser_first_name'),
        ('app', '0004_merge_20250426_1146'),
    ]

    operations = [
    ]
