# Generated by Django 3.0.5 on 2025-04-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20250428_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='course_name',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course_name',
            new_name='course_id',
        ),
    ]
