# Generated by Django 3.0.5 on 2025-05-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20250428_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='course_id',
        ),
    ]
