# Generated by Django 5.1.4 on 2025-05-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20250426_1310'),
        ('app', '0005_staff'),
        ('app', '0009_remove_staff_course_id'),
    ]

    operations = [
    ]
