# Generated by Django 3.0.5 on 2025-05-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_staff'),
        ('app', '0009_remove_staff_course_id'),
    ]

    operations = [
    ]
