# Generated by Django 3.0.5 on 2025-05-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20250505_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='session_year_id',
        ),
        migrations.AlterField(
            model_name='subject',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff'),
        ),
    ]
