# Generated by Django 3.0.5 on 2025-05-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_20250503_2046'),
        ('app', '0014_auto_20250507_2029'),
    ]

    operations = [
    ]
