# Generated by Django 5.1.4 on 2025-05-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_staff_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_feedback',
            name='feedback_replay',
        ),
    ]
