# Generated by Django 5.1.4 on 2025-05-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_staff_feedback_feedback_replay'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_feedback',
            name='feedback_replay',
            field=models.TextField(blank=True),
        ),
    ]
