# Generated by Django 5.1.4 on 2025-06-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_staff_feedback_feedback_replay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_feedback',
            old_name='feedback_replay',
            new_name='feedback_reply',
        ),
    ]
