# Generated by Django 3.0.5 on 2025-06-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20250602_2000'),
        ('app', '0025_rename_feedback_replay_staff_feedback_feedback_reply'),
    ]

    operations = [
    ]
