# Generated by Django 3.0.5 on 2025-06-21 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_student_feedback'),
        ('app', '0029_auto_20250621_0810'),
    ]

    operations = [
    ]
