# Generated by Django 3.0.5 on 2025-07-25 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20250725_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_report',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.student'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(default='General Leave', max_length=50),
        ),
        migrations.AlterField(
            model_name='result',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
        migrations.AlterField(
            model_name='staff_feedback',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff'),
        ),
        migrations.AlterField(
            model_name='staff_leave',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff'),
        ),
        migrations.AlterField(
            model_name='staff_notification',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff'),
        ),
        migrations.AlterField(
            model_name='student_feedback',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
        migrations.AlterField(
            model_name='student_leave',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
        migrations.AlterField(
            model_name='student_notification',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff'),
        ),
    ]
